CREATE TABLE MEMBER (
	ID VARCHAR2(30 BYTE), 
	PWD VARCHAR2(30 BYTE) NOT NULL , 
	EMAIL VARCHAR2(50 BYTE) NOT NULL , 
	GENDER CHAR(1 BYTE) NOT NULL , 
	JOINDATE DATE DEFAULT sysdate, 
	PHONENUM VARCHAR2(20 BYTE), 
	CONSTRAINT "MEMBER_ID_PK" PRIMARY KEY ("ID")
);